### ISSUE TITLE
adding version install arg doesnt work.

### ISSUE THREAD

**Issue by bargoldenberg** [webdriverio-community/wdio-edgedriver-service#127]
Hi, when i run` EDGECHROMIUMDRIVER_VERSION=110.0.1587.41 npm install wdio-edgedriver-service --save-dev`
it automatically installs version 91, anyway on macOS i was able to manually swap the msedgedriver file with a updated one and everything worked, but on my linux machine it doesn't.

**Comment by christian-bromann** [comment]
We are testing the successfully in CI with the following Github Workflow step:

```yaml
    - name: Install Dependencies
      run: npm ci
      env:
        EDGECHROMIUMDRIVER_VERSION: 109.0.1518.78
```

How is this setup different from yours? We don't need to swap anything.
